name: stack-observabilidade

networks:
  telemetry_net:
    name: telemetry_net
    driver: bridge

volumes:
    loki_volume:
      name: loki_volume

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./infra/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3333:3000"
    networks:
      - telemetry_net
    depends_on:
      - otel-collector
      - jaeger
      - tempo
      - loki
      - prometheus

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.86.0
    command: [ "--config=/etc/collector.yaml" ]
    ports:
      - "8889:8889" # Prometheus metrics exporter (scrape endpoint)
      - "4317:4317" # Endpoint where application will be pushing telemetry data, e.g. logs, traces, and metrics.
      - "4318:4318" # Endpoint where application will be pushing telemetry data, e.g. logs, traces, and metrics.
    volumes:
      - ./infra/otel-collector-config.yaml:/etc/collector.yaml
    depends_on:
      - jaeger
      - tempo
      - loki
    networks:
      - telemetry_net

  jaeger:
    container_name: jaeger
    image: jaegertracing/jaeger:2.3.0 # prod
    # image: jaegertracing/all-in-one:latest # dev
    ports:
      - "16686:16686"  # UI
    restart: unless-stopped
    networks:
      - telemetry_net

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./infra/tempo.yaml:/etc/tempo.yaml
    networks:
      - telemetry_net

  loki:
    container_name: loki
    image: grafana/loki:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "3100:3100"
    volumes:
      - ./infra/loki-config.yaml:/etc/loki/local-config.yaml:ro
      - loki_volume:/tmp
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - telemetry_net

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./infra/app-dev-logs.log:/var/log/app-dev-logs.log
      - ./infra/promtail-config.yaml:/etc/promtail/promtail-config.yaml:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - telemetry_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus-config.yaml:/etc/prometheus/prometheus.yaml
    depends_on:
      - otel-collector
      - loki
    networks:
      - telemetry_net