receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    send_batch_size: 1024
    timeout: 5s

exporters:
  logging:
    loglevel: info

  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # otlp:
  #   # endpoint: tempo:4317
  #   endpoint: tempo:9095
  #   tls:
  #     insecure: true

  otlp:
    endpoint: tempo:4319
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tls:
      insecure: true

service:
  pipelines:      
    logs:
      receivers: [http, otlp]
      processors: [batch]
      exporters: [loki]

    traces:
      receivers: [http, otlp]
      processors: [batch]
      # exporters: [otlp/jaeger]
      exporters: [logging, otlp, otlp/jaeger]
      # exporters: [logging, otlp]
      # exporters: [otlp]

    metrics:
      receivers: [http, otlp]
      processors: [batch]
      exporters: [prometheus]