global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:      
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']


# NOTE: Application will push metrics to port 4317,
# then otel-collector-config prometheus part will scrape metrics from there and put to port 8889,
# and then from there prometheus-config will scrape metrics from port 8889 and forward
# them to prometheus that grafana can visualize from port 9090 (prometheus port).